# Generated by Django 3.0 on 2020-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('Fid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('BatchInCharge', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('AdmNo', models.IntegerField(blank=True, max_length=10, null=True)),
                ('AdmDate', models.DateField()),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Guardian', models.CharField(max_length=20)),
                ('Mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Batch', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
