# Generated by Django 3.0 on 2020-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Blood',
            field=models.CharField(default='O+', max_length=5),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Designation',
            field=models.CharField(default='trainer', max_length=15),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Joiningdate',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Password',
            field=models.CharField(max_length=1),
        ),
    ]
