# Generated by Django 3.0 on 2020-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200113_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Rollno',
            field=models.IntegerField(default=1),
        ),
    ]
