# Generated by Django 3.0 on 2020-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Category',
            field=models.CharField(default='Catholic', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='Course',
            field=models.CharField(default='JSD1', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='Qualification',
            field=models.CharField(default='BSc', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='Religion',
            field=models.CharField(default='Christian', max_length=10),
        ),
    ]
