# Generated by Django 3.0 on 2020-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200113_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Leavetype', models.CharField(max_length=15)),
                ('Day', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Session', models.CharField(max_length=10)),
                ('Leavereason', models.CharField(max_length=30)),
                ('Leavedescription', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
