# Generated by Django 3.0 on 2020-01-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_leave_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessmentname', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('Subject', models.CharField(max_length=10)),
                ('Facultyname', models.CharField(max_length=10)),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Mark', models.FloatField()),
            ],
        ),
    ]
