# Generated by Django 3.0 on 2020-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='Facultyname',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='Mark',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='Subject',
        ),
        migrations.AddField(
            model_name='assessment',
            name='Sub1',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Sub2',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Sub3',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Sub4',
            field=models.FloatField(default='0'),
        ),
    ]
