# Generated by Django 3.0 on 2020-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200114_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='Total',
            field=models.FloatField(default='0'),
        ),
    ]
