# Generated by Django 3.0 on 2020-01-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_assessment_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='RollNo',
        ),
    ]
