# Generated by Django 3.0 on 2020-01-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_assessment_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
