# Generated by Django 3.0 on 2020-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200114_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='Batch',
            field=models.CharField(default='JSD2', max_length=10),
        ),
    ]
