# Generated by Django 3.0 on 2020-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_assessment_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Status_h1', models.CharField(max_length=10)),
                ('Status_h2', models.CharField(max_length=10)),
                ('Status_h3', models.CharField(max_length=10)),
                ('Status_h4', models.CharField(max_length=10)),
            ],
        ),
    ]
